#!/bin/bash
python <<< "from griddiagrams.core import print_clean, print_vertlist, gridstate_finder_commute
from griddiagrams.search import find_nice_for_all_knots
from griddiagrams.data import load_knot_data
load_knot_data()
find_nice_for_all_knots(gridstate_finder_commute, '../output_images/')
"
